### ISSUE TITLE
Nagy a probléma

### ISSUE THREAD

**Issue by csutora** [Posfay/Bubble-Sort-Visualization#1]
vannak azonos magasságúak, és így csúnya. Kérnék egy módot, amiben minden magasságból csak egy van, egy szép átlót alkotva kirakás után, emellett egy gombot, ami végteleníti a folyamatot, szóval rendezés után újrakezdi, hogy nézhessem órákon keresztül, és ha még mindig van időd, akkor akár elemszám változtatót is tehetnél bele. És ha még mindig nincs jobb dolgod akkor színállítót kérek pontos rgb értékekkel. Ennyi 🗡 💋

**Comment by Posfay** [comment]
challenge accepted

**Comment by Posfay** [comment]
kesz, nezd csak meg :p
